# Vous pouvez générer directement un fichier de configuration via l'interface disponible ici:
# https://www.facturation.pro/account/api
#
# Sinon il vous suffit de récupérer vos informations API et les renseigner dans ce fichier
# et l'enregistrer sous le nom config.yml
#
---
  :api_id: 0
  :api_key: "XXX"
  :directory: './downloads'
  :firms:
    # liste des entreprises à récupérer dans ce compte
    - :firm_id: XX
      :subdirectory: "my firm"
#    - firm_id: YY
#      subdirectory: "other corp"
#    - firm_id: ZZ
#      subdirectory: "third corp"

